spring:
  application:
    name: cvapp
  datasource:
    url: jdbc:postgresql://localhost:5432/cvapp
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      schema-locations: classpath:database/schema.sql
langchain4j:
  open-ai:
    chat-model:
      api-key:
      model-name: gpt-3.5-turbo
      temperature: '0.7'
      response-format: json_object
      log-requests: true
      log-responses: true
logging:
  level:
    dev:
      langchain4j: DEBUG
      ai4j:
        openai4j: DEBUG
